--TODO: Вырезать этот дерьмокод отовсюду

--------------------------------------------------------------------------------------------------------
--/У Меченого есть деньги
--------------------------------------------------------------------------------------------------------
function has_1000(actor, npc)
	return false
end

function has_10000(actor, npc)
	return false
end

function has_20000(actor, npc)
	return false
end

function has_30000(actor, npc)
	return false
end

function has_40000(actor, npc)
	return false
end

function has_50000(actor, npc)
	return false
end

function has_60000(actor, npc)
	return false
end

function has_80000(actor, npc)
	return false
end


--------------------------------------------------------------------------------------------------------
--/Передача денег
--------------------------------------------------------------------------------------------------------
function relocate_1000(trader, actor)
end

function relocate_10000(trader, actor)
end

function relocate_20000(trader, actor)
end

function relocate_30000(trader, actor)
end

function relocate_40000(trader, actor)
end

function relocate_50000(trader, actor)
end
function relocate_60000(trader, actor)
end

--------------------------------------------------------------------------------------------------------
--/Восстановление отношений с одиночками
--------------------------------------------------------------------------------------------------------
function bad_relation_stalker(trader, actor)
	return false 
end

function bad_relation_30000(trader, actor)
	return false 
end

function bad_relation_10000(trader, actor)
	return false
end

function bad_relation_20000(trader, actor)
	return false
end


function bad_relation_40000(trader, actor)
	return false
end

function bad_relation_50000(trader, actor)
	return false
end

function bad_relation_60000(trader, actor)
	return false
end

function repair_relation_stalker(trader, actor)
end


--------------------------------------------------------------------------------------------------------
--/Восстановление отношений с долговцами
--------------------------------------------------------------------------------------------------------
function bad_relation_dolg()
	return false
end

function give_info_dolg()
end

function repair_relation_dolg()
end
--------------------------------------------------------------------------------------------------------
--/Восстановление отношений со свободовцами 
--------------------------------------------------------------------------------------------------------

function bad_relation_freedom()
	return false
end

function give_info_free(first_speaker, second_speaker)
end

function repair_relation_free(trader, actor)
end

--------------------------------------------------------------------------------------------------------
--/Восстановление отношений с бандитами через торговца бандитов Барыгу
--------------------------------------------------------------------------------------------------------
function bad_relation_bandit(trader, actor)
	return false
end

function bad_relation_bandit_10000(trader, actor)
end

function bad_relation_bandit_30000(trader, actor)
	return false
end

function bad_relation_bandit_50000(trader, actor)
	return false
end

function repair_relation_bandit(trader, actor)
end
