--Сборщик мусора. Немного чистит память. Взял из dsh мода.


function attach( sm )
	sm:subscribe({ signal = "on_after_save",	fun = this.cleanup })
	sm:subscribe({ signal = "on_first_update",	fun = this.cleanup })
end


function cleanup()
--log1("Memory used by LUA BEFORE cleanup: "..tostring(collectgarbage( "count" )).." Kb")
	collectgarbage( "collect" )
--log1("Memory used by LUA AFTER cleanup: "..tostring(collectgarbage( "count" )).." Kb")
end
